name: RPTool
version: '${project.version}'
author: chelop
main: me.chelop.rptool.RPTool
api-version: '1.16'

commands:
  do:
    usage: /do <action>
    permission: rt.rp
  me:
    usage: /me <action>
    permission: rt.rp
  todo:
    usage: /todo <message*action>
    permission: rt.rp
  try:
    usage: /try <action>
    permission: rt.rp
  rt:
    permission: rt.reload
  n:
    usage: /n <message>
    permission: rt.rp
    aliases:
      - b
  w:
    usage: /w <player> <message>
    permission: rt.w
