# # # # # # # # # # # # # # # # # # # # # # # #
# RPTool, 2023, by chelop                     #
# License: Apache 2.0                         #
# http://www.apache.org/licenses/LICENSE-2.0  #
# # # # # # # # # # # # # # # # # # # # # # # #

#    The range of the visible messages
range:
  enabled: true
  range: 25

#    Mistakes & Errors
no-permissions: "&cУ вас нет разрешений на использование этой команды!"
not-enough-arguments: "&cОшибка: Недостаточно аргументов."
no-heard: "&eНикто тебя не услышал."
player-only: "&cОшибка: Эта команда может быть выполнена только игроком."

#    Reloading the config
config-reload: "&aКонфигурация успешно перезагружена."

#    Commands
do: "&d%action% %player%"
me: "&d%player% %action%"
n: "&6(( %player%: %message% ))"
todo: "&d%action%, %player% сказал(а): &3%message%"
try: "&d%player% %action% &7| %result%"
whisper:
  whisper-yourself: "&cОшибка: Ты не можешь шептать сам себе."
  player-not-found: "&cОшибка: Игрок не найден."

  you-whispered: "&7Ты прошептал %player%: %message%"
  whispered-you: "&7%player% прошептал тебе: %message%"

